project:
  name: quickstart-awx
  owner: quickstart-eng@amazon.com
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  shorten_stack_name: true
  regions:
  - us-east-1
  - us-west-1
  #- ap-south-1
  - eu-west-3
  - eu-west-1
  - ap-northeast-1
  - ap-northeast-2
  - sa-east-1
  - ca-central-1
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - us-east-2
  parameters:
    AWXAdminPassword: $[taskcat_genpass_8A]
    AWXAdminUsername: admin
    AWXGitHubRepo: https://github.com/ansible/awx.git
    AvailabilityZones: $[taskcat_genaz_2]
    ClusterSize: 2
    DBInstanceClass: db.t3.medium
    InstanceType: t3.large
    MasterUserPassword: $[taskcat_genpass_8A]
    MasterUsername: cidbadmin
    QSS3BucketName: $[taskcat_autobucket]
    QSS3KeyPrefix: quickstart-awx/
    QSS3BucketRegion: $[taskcat_current_region]
    BackupRetentionPeriod: 0
tests:
  awx-v17-1-0:
    template: templates/awx-master.template
    parameters:
      AWXVersion: 17.1.0
      KeyPairName: overridden
      RemoteAccessCIDR: overridden
    regions:
    - eu-west-1
